<?php 


if (function_exists('acf_add_local_field_group')) {

    acf_add_local_field_group(array(
    'key' => 'group_simpleview_events_general_settings',
    'title' => __('Simpleview Events Settings', 'modularity-simpleview-events'),
    'fields' => array(
        0 => array(
            'key' => 'field_simpleview_events_display_name',
            'label' => __('Display Name', 'modularity-simpleview-events'),
            'name' => 'display_name',
            'aria-label' => '',
            'type' => 'text',
            'instructions' => __('The name shown on the frontend (archive title, breadcrumbs). Leave empty to use the default \'Simpleview Events\'.', 'modularity-simpleview-events'),
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'default_value' => '',
            'maxlength' => '',
            'allow_in_bindings' => 0,
            'placeholder' => 'Simpleview Events',
            'prepend' => '',
            'append' => '',
        ),
        1 => array(
            'key' => 'field_simpleview_events_slug',
            'label' => __('Slug', 'modularity-simpleview-events'),
            'name' => 'slug',
            'aria-label' => '',
            'type' => 'text',
            'instructions' => __('The URL slug for the archive and posts. Auto-generated from Display Name, but can be customized. Don\'t forget to flush permalinks after changing (Settings > Permalinks > Save).', 'modularity-simpleview-events'),
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'default_value' => '',
            'maxlength' => '',
            'allow_in_bindings' => 0,
            'placeholder' => 'simpleview-event',
            'prepend' => '',
            'append' => '',
        ),
        2 => array(
            'key' => 'field_simpleview_events_api_base_url',
            'label' => __('API Base URL', 'modularity-simpleview-events'),
            'name' => 'api_base_url',
            'aria-label' => '',
            'type' => 'url',
            'instructions' => __('The base URL for the Simpleview API endpoint.', 'modularity-simpleview-events'),
            'required' => 1,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'default_value' => '',
            'placeholder' => 'https://api.simpleview.com',
        ),
        3 => array(
            'key' => 'field_simpleview_events_api_key',
            'label' => __('API Key', 'modularity-simpleview-events'),
            'name' => 'api_key',
            'aria-label' => '',
            'type' => 'text',
            'instructions' => __('The API key for authenticating with Simpleview API.', 'modularity-simpleview-events'),
            'required' => 1,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'default_value' => '',
            'placeholder' => '',
        ),
        4 => array(
            'key' => 'field_simpleview_events_sync_frequency',
            'label' => __('Sync Frequency', 'modularity-simpleview-events'),
            'name' => 'sync_frequency',
            'aria-label' => '',
            'type' => 'select',
            'instructions' => __('How often to automatically sync events from Simpleview API.', 'modularity-simpleview-events'),
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'choices' => array(
                'hourly' => 'Hourly',
                'twicedaily' => 'Twice Daily',
                'daily' => 'Daily',
            ),
            'default_value' => 'daily',
            'allow_null' => 0,
            'multiple' => 0,
            'ui' => 0,
            'return_format' => 'value',
            'ajax' => 0,
            'placeholder' => '',
        ),
        5 => array(
            'key' => 'field_simpleview_events_manual_sync',
            'label' => __('Manual Sync', 'modularity-simpleview-events'),
            'name' => 'manual_sync',
            'aria-label' => '',
            'type' => 'message',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'message' => '<button type="button" id="simpleview-events-manual-sync" class="button button-primary">Sync Now</button>',
            'new_lines' => 'wpautop',
            'esc_html' => 0,
        ),
    ),
    'location' => array(
        0 => array(
            0 => array(
                'param' => 'options_page',
                'operator' => '==',
                'value' => 'simpleview-events-settings',
            ),
        ),
    ),
    'menu_order' => 0,
    'position' => 'normal',
    'style' => 'default',
    'label_placement' => 'top',
    'instruction_placement' => 'label',
    'hide_on_screen' => '',
    'active' => true,
    'description' => '',
    'show_in_rest' => 0,
    'display_title' => '',
    'acfe_autosync' => array(
        0 => 'json',
    ),
    'acfe_form' => 0,
    'acfe_meta' => '',
    'acfe_note' => '',
));

}
