<?php


if (function_exists('acf_add_local_field_group')) {

    acf_add_local_field_group(array(
        'key' => 'group_simpleview_events_general_settings',
        'title' => __('Simpleview Events Settings', 'modularity-simpleview-events'),
        'fields' => array(
            0 => array(
                'key' => 'field_simpleview_events_api_base_url',
                'label' => __('API Base URL', 'modularity-simpleview-events'),
                'name' => 'api_base_url',
                'aria-label' => '',
                'type' => 'url',
                'instructions' => __('The base URL for the Simpleview API endpoint.', 'modularity-simpleview-events'),
                'required' => 1,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => __('https://api.simpleview.com', 'modularity-simpleview-events'),
            ),
            1 => array(
                'key' => 'field_simpleview_events_api_key',
                'label' => __('API Key', 'modularity-simpleview-events'),
                'name' => 'api_key',
                'aria-label' => '',
                'type' => 'password',
                'instructions' => __('The API key for authenticating with Simpleview API.', 'modularity-simpleview-events'),
                'required' => 1,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
            ),
            2 => array(
                'key' => 'field_simpleview_events_sync_frequency',
                'label' => __('Sync Frequency', 'modularity-simpleview-events'),
                'name' => 'sync_frequency',
                'aria-label' => '',
                'type' => 'select',
                'instructions' => __('How often to automatically sync events from Simpleview API.', 'modularity-simpleview-events'),
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'choices' => array(
                    'hourly' => __('Hourly', 'modularity-simpleview-events'),
                    'twicedaily' => __('Twice Daily', 'modularity-simpleview-events'),
                    'daily' => __('Daily', 'modularity-simpleview-events'),
                ),
                'default_value' => 'daily',
                'allow_null' => 0,
                'multiple' => 0,
                'ui' => 0,
                'return_format' => 'value',
                'ajax' => 0,
                'placeholder' => '',
                'create_options' => 0,
                'save_options' => 0,
                'allow_custom' => 0,
                'search_placeholder' => '',
            ),
            3 => array(
                'key' => 'field_simpleview_events_use_mock_data',
                'label' => __('Use Mock Data', 'modularity-simpleview-events'),
                'name' => 'use_mock_data',
                'aria-label' => '',
                'type' => 'true_false',
                'instructions' => __('Use local mock JSON file instead of API. Enable this to test with mock data before switching to the live API.', 'modularity-simpleview-events'),
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'message' => '',
                'default_value' => 0,
                'ui' => 1,
                'ui_on_text' => '',
                'ui_off_text' => '',
            ),
            4 => array(
                'key' => 'field_simpleview_events_archive_retention_days',
                'label' => __('Archive Retention Days', 'modularity-simpleview-events'),
                'name' => 'archive_retention_days',
                'aria-label' => '',
                'type' => 'number',
                'instructions' => __('Number of days to keep archived posts before permanent deletion. Posts removed from the API will be archived, then deleted after this period.', 'modularity-simpleview-events'),
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => 30,
                'min' => 1,
                'max' => 365,
                'placeholder' => '',
                'step' => 1,
                'prepend' => '',
                'append' => __('days', 'modularity-simpleview-events'),
            ),
            5 => array(
                'key' => 'field_simpleview_events_manual_sync',
                'label' => __('Manual Sync', 'modularity-simpleview-events'),
                'name' => '',
                'aria-label' => '',
                'type' => 'message',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'message' => __('<button type="button" id="simpleview-events-manual-sync" class="button button-primary">Sync Now</button>', 'modularity-simpleview-events'),
                'new_lines' => 'wpautop',
                'esc_html' => 0,
            ),
        ),
        'location' => array(
            0 => array(
                0 => array(
                    'param' => 'options_page',
                    'operator' => '==',
                    'value' => 'simpleview-events-settings',
                ),
            ),
        ),
        'menu_order' => 0,
        'position' => 'normal',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => '',
        'active' => true,
        'description' => '',
        'show_in_rest' => 0,
        'display_title' => '',
        'acfe_autosync' => array(
            0 => 'json',
        ),
        'acfe_form' => 0,
        'acfe_meta' => '',
        'acfe_note' => '',
    ));
}
