<?php 

if (function_exists('acf_add_local_field_group')) {
    acf_add_local_field_group(array(
    'key' => 'group_simpleview_events_general_settings',
    'title' => __('Simpleview Events Settings', 'modularity-simpleview-events'),
    'fields' => array(
        0 => array(
            'key' => 'field_simpleview_events_api_base_url',
            'label' => __('API Base URL', 'modularity-simpleview-events'),
            'name' => 'api_base_url',
            'aria-label' => '',
            'type' => 'url',
            'instructions' => __('The base URL for the Simpleview API endpoint (without query parameters).', 'modularity-simpleview-events'),
            'required' => 1,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'default_value' => '',
            'placeholder' => 'https://api.example.com/endpoint',
        ),
        1 => array(
            'key' => 'field_simpleview_events_api_key',
            'label' => __('API Key (LicenceKey)', 'modularity-simpleview-events'),
            'name' => 'api_key',
            'aria-label' => '',
            'type' => 'password',
            'instructions' => __('The LicenceKey for authenticating with the Simpleview API.', 'modularity-simpleview-events'),
            'required' => 1,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'default_value' => '',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
        ),
        2 => array(
            'key' => 'field_simpleview_events_db_owner_id_list',
            'label' => __('DB Owner ID List', 'modularity-simpleview-events'),
            'name' => 'db_owner_id_list',
            'aria-label' => '',
            'type' => 'text',
            'instructions' => __('The DBOwnerIdList parameter sent to the API (e.g. "143").', 'modularity-simpleview-events'),
            'required' => 1,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '50',
                'class' => '',
                'id' => '',
            ),
            'default_value' => '',
            'placeholder' => '143',
            'prepend' => '',
            'append' => '',
        ),
        3 => array(
            'key' => 'field_simpleview_events_distribution_channel_id',
            'label' => __('Distribution Channel ID', 'modularity-simpleview-events'),
            'name' => 'distribution_channel_id',
            'aria-label' => '',
            'type' => 'text',
            'instructions' => __('The DistributionChannelId parameter sent to the API (e.g. "634573").', 'modularity-simpleview-events'),
            'required' => 1,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '50',
                'class' => '',
                'id' => '',
            ),
            'default_value' => '',
            'placeholder' => '634573',
            'prepend' => '',
            'append' => '',
        ),
        4 => array(
            'key' => 'field_simpleview_events_language_id',
            'label' => __('Language ID', 'modularity-simpleview-events'),
            'name' => 'language_id',
            'aria-label' => '',
            'type' => 'text',
            'instructions' => __('The LanguageId parameter (e.g. "sv" for Swedish).', 'modularity-simpleview-events'),
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '50',
                'class' => '',
                'id' => '',
            ),
            'default_value' => 'sv',
            'placeholder' => 'sv',
            'prepend' => '',
            'append' => '',
        ),
        5 => array(
            'key' => 'field_simpleview_events_country_id',
            'label' => __('Country ID', 'modularity-simpleview-events'),
            'name' => 'country_id',
            'aria-label' => '',
            'type' => 'text',
            'instructions' => __('The CountryId parameter (e.g. "SE" for Sweden).', 'modularity-simpleview-events'),
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '50',
                'class' => '',
                'id' => '',
            ),
            'default_value' => 'SE',
            'placeholder' => 'SE',
            'prepend' => '',
            'append' => '',
        ),
        6 => array(
            'key' => 'field_simpleview_events_test_connection',
            'label' => __('Test Connection', 'modularity-simpleview-events'),
            'name' => '',
            'aria-label' => '',
            'type' => 'message',
            'instructions' => __('Save settings first, then test the connection to verify your API configuration. Shows which media channels are available.', 'modularity-simpleview-events'),
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'message' => sprintf(
                '<button type="button" id="simpleview-events-test-connection" class="button button-secondary">%s</button><div id="simpleview-events-test-result"></div>',
                esc_html__('Test Connection', 'modularity-simpleview-events')
            ),
            'new_lines' => '',
            'esc_html' => 0,
        ),
        7 => array(
            'key' => 'field_simpleview_events_archive_retention_days',
            'label' => __('Archive Retention Days', 'modularity-simpleview-events'),
            'name' => 'archive_retention_days',
            'aria-label' => '',
            'type' => 'number',
            'instructions' => __('Number of days to keep archived posts before permanent deletion. Posts removed from the API will be archived, then deleted after this period.', 'modularity-simpleview-events'),
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'default_value' => 30,
            'min' => 1,
            'max' => 365,
            'placeholder' => '',
            'step' => 1,
            'prepend' => '',
            'append' => __('days', 'modularity-simpleview-events'),
        ),
        8 => array(
            'key' => 'field_simpleview_events_manual_sync',
            'label' => __('Manual Sync', 'modularity-simpleview-events'),
            'name' => '',
            'aria-label' => '',
            'type' => 'message',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'message' => __('<button type="button" id="simpleview-events-manual-sync" class="button button-primary">Sync Now</button>', 'modularity-simpleview-events'),
            'new_lines' => 'wpautop',
            'esc_html' => 0,
        ),
    ),
    'location' => array(
        0 => array(
            0 => array(
                'param' => 'options_page',
                'operator' => '==',
                'value' => 'simpleview-events-settings',
            ),
        ),
    ),
    'menu_order' => 0,
    'position' => 'normal',
    'style' => 'default',
    'label_placement' => 'top',
    'instruction_placement' => 'label',
    'hide_on_screen' => '',
    'active' => true,
    'description' => '',
    'show_in_rest' => 0,
    'display_title' => '',
    'acfe_autosync' => array(
        0 => 'json',
    ),
    'acfe_form' => 0,
    'acfe_meta' => '',
    'acfe_note' => '',
));
}